/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.pojo.AssignedMonths;
import controller.pojo.Department;
import controller.pojo.Manager;
import controller.pojo.Member;
import controller.pojo.PersonalInfo;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.dao.AssignedMonthsServices;
import model.dao.DeptNmaesServices;
import model.dao.MemberServices;
import model.dao.OffDaysServices;
import model.dao.PersonalInfoServices;

/**
 *
 * @author OLEE
 */
public class EditMemberView extends javax.swing.JFrame {

    /**
     * Creates new form PersonalInfo
     */
    MemberServices memberServices = new MemberServices();
    DeptNmaesServices deptNmaesServices = new DeptNmaesServices();
    
    //for updating
    private int id = 0;

    ArrayList<String> deptNames = (ArrayList<String>) deptNmaesServices.getDepartmentList();
    
    Manager manager;
    
    public EditMemberView(Manager manager) {

        initComponents();
        setLocationRelativeTo(null);
        this.manager = manager;
        this.setTitle("Registrar Memebr");
        t_crdNotoSrch.setBackground(new Color(0, 0, 0, 0));
        t_name.setBackground(new Color(0, 0, 0, 0));
        lbl_bg.setBackground(new Color(0, 0, 0, 0));
        t_cntNum.setBackground(new Color(0, 0, 0, 0));
        t_email.setBackground(new Color(0, 0, 0, 0));
        t_regNo.setBackground(new Color(0, 0, 0, 0));
        t_session.setBackground(new Color(0, 0, 0, 0));
        t_cardNo.setBackground(new Color(0, 0, 0, 0));

        com_depts.setBackground(new Color(0, 0, 0, 0));
        com_type.setBackground(new Color(0, 0, 0, 0));

        pnl_sideBar.setBackground(new Color(0, 0, 0, 100));

        for (String deptNames : deptNames) {
            com_depts.addItem(deptNames);
        }
    }
    public EditMemberView() {
        
    }
    private void designTable(JTable tableName) {
        tableName.getTableHeader().setForeground(new Color(255, 255, 255));
        tableName.getTableHeader().setBackground(Color.BLACK);
        tableName.getTableHeader().setForeground(Color.black);

        ((DefaultTableCellRenderer) tableName.getDefaultRenderer(Object.class)).setOpaque(false);

        tableName.setBackground(new Color(0, 0, 0));
        //jScrollPane1.setBackground(new Color(0, 0, 0));
        //jScrollPane1.getViewport().setOpaque(false);
        tableName.setShowGrid(true);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableName.setDefaultRenderer(String.class, centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_sideBar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        sideBtn_member1 = new javax.swing.JLabel();
        sideBtn_member2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        t_cntNum = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        t_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        t_regNo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        t_session = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lbl_msgsSrch = new javax.swing.JLabel();
        btn_srch = new javax.swing.JButton();
        com_depts = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        t_cardNo = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        com_type = new javax.swing.JComboBox<>();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        t_crdNotoSrch = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        lbl_msgs = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_sideBar.setBackground(new java.awt.Color(0, 0, 0));
        pnl_sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setOpaque(true);
        pnl_sideBar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 10, 40));

        sideBtn_member1.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_member1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_member1.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_member1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_member1.setText("Add Member");
        sideBtn_member1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_member1.setOpaque(true);
        pnl_sideBar.add(sideBtn_member1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 40));

        sideBtn_member2.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_member2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_member2.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_member2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_member2.setText("Delete Member");
        sideBtn_member2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_member2.setOpaque(true);
        pnl_sideBar.add(sideBtn_member2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 40));

        jLabel14.setOpaque(true);
        pnl_sideBar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 10, 40));

        getContentPane().add(pnl_sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 650));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Personal Information");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 620, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 1020, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 70, 30));

        t_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_name.setForeground(new java.awt.Color(255, 255, 255));
        t_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_name.setBorder(null);
        t_name.setOpaque(false);
        getContentPane().add(t_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 250, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 250, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 70, 30));

        t_cntNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_cntNum.setForeground(new java.awt.Color(255, 255, 255));
        t_cntNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_cntNum.setBorder(null);
        t_cntNum.setOpaque(false);
        getContentPane().add(t_cntNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 250, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 250, 10));

        t_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_email.setForeground(new java.awt.Color(255, 255, 255));
        t_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_email.setBorder(null);
        t_email.setOpaque(false);
        getContentPane().add(t_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 250, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 70, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 250, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Department");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 80, 30));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 250, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Reg. No");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 80, 30));

        t_regNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_regNo.setForeground(new java.awt.Color(255, 255, 255));
        t_regNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_regNo.setBorder(null);
        t_regNo.setOpaque(false);
        getContentPane().add(t_regNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 120, 250, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 250, 10));

        t_session.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_session.setForeground(new java.awt.Color(255, 255, 255));
        t_session.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_session.setBorder(null);
        t_session.setOpaque(false);
        getContentPane().add(t_session, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 170, 250, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Session");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 80, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, 250, 10));
        getContentPane().add(lbl_msgsSrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 140, 30));

        btn_srch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_srch.setForeground(new java.awt.Color(255, 255, 255));
        btn_srch.setText("Search");
        btn_srch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_srch.setContentAreaFilled(false);
        btn_srch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_srchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_srch, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 100, 40));

        com_depts.setBackground(new java.awt.Color(255, 51, 51));
        com_depts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        com_depts.setForeground(new java.awt.Color(0, 102, 51));
        com_depts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department" }));
        com_depts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(com_depts, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 250, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Card No");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 70, 30));

        t_cardNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_cardNo.setForeground(new java.awt.Color(255, 255, 255));
        t_cardNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_cardNo.setBorder(null);
        t_cardNo.setOpaque(false);
        getContentPane().add(t_cardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 250, 30));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 250, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Type");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 70, 30));

        com_type.setBackground(new java.awt.Color(255, 51, 51));
        com_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        com_type.setForeground(new java.awt.Color(0, 102, 51));
        com_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select type", "Regular", "Extra" }));
        com_type.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(com_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, 250, 30));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, 250, 10));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 10, 490));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Which  card to edit?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 170, 30));

        t_crdNotoSrch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_crdNotoSrch.setForeground(new java.awt.Color(255, 255, 255));
        t_crdNotoSrch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_crdNotoSrch.setBorder(null);
        t_crdNotoSrch.setOpaque(false);
        getContentPane().add(t_crdNotoSrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 250, 30));

        btn_update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update");
        btn_update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_update.setContentAreaFilled(false);
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 390, 100, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Card No");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 70, 30));

        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 360, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Pevious Informations");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 170, 30));
        getContentPane().add(lbl_msgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 140, 30));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 360, 10));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 250, 10));

        lbl_bg.setBackground(new java.awt.Color(0, 102, 102));
        lbl_bg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_bg.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bg.setOpaque(true);
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_srchActionPerformed
        // TODO add your handling code here:

        try {
            int carNo = Integer.parseInt(t_crdNotoSrch.getText().trim());

            if (memberServices.isCardExists(carNo)) {
                Member member = memberServices.getMemberByCardNo(carNo);
                setValusInField(member);
                id = member.getId();
            } else {
                lbl_msgsSrch.setText("Card does not exists");
                lbl_msgsSrch.setForeground(Color.red);
            }
        } catch (NumberFormatException e) {
            lbl_msgsSrch.setText("Enter valid card number");
            lbl_msgsSrch.setForeground(Color.red);
        }


    }//GEN-LAST:event_btn_srchActionPerformed

    private void setValusInField(Member member) {
        t_name.setText(member.getName());
        t_cntNum.setText(member.getMobile());
        t_email.setText(member.getEmail());
        com_depts.setSelectedItem(member.getDeptName());
        t_regNo.setText(member.getRegNum());
        t_session.setText(member.getSession());
        t_cardNo.setText(member.getCardNo() + "");
        com_type.setSelectedItem(member.getMembershipType());
    }
    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String name = t_name.getText().trim();
        String mobile = t_cntNum.getText().trim();
        String email = t_email.getText().trim();
        String deptName = com_depts.getSelectedItem().toString();
        String regNo = t_regNo.getText().trim();
        String session = t_session.getText().trim();
        int cardNo = 0;
        System.out.println(mobile);
        try {
            cardNo = Integer.parseInt(t_cardNo.getText().trim());
        } catch (NumberFormatException e) {
            lbl_msgsSrch.setText("Enter valid card no");
            lbl_msgsSrch.setForeground(Color.red);
        }
        String memberType = com_type.getSelectedItem().toString();

        if (name.isEmpty() || mobile.isEmpty() || email.isEmpty() || deptName.isEmpty() || regNo.isEmpty() || session.isEmpty()) {
            lbl_msgsSrch.setText("Fill out all the fields");
            lbl_msgsSrch.setForeground(Color.red);
        } else {
                System.out.println(mobile);
                Member member = new Member(name, mobile, email, deptName, regNo, session, cardNo, memberType, "Inactive", new Date(System.currentTimeMillis()));

                if (memberServices.update(member,id) > 0) {
                    System.out.println(mobile);
                    lbl_msgsSrch.setText("Successfully Updated");
                    lbl_msgsSrch.setForeground(Color.GREEN);
//                    addToTable(member);
                } else {
                    lbl_msgsSrch.setText("Not Updated");
                    lbl_msgsSrch.setForeground(Color.red);
                }
            
        }
    }//GEN-LAST:event_btn_updateActionPerformed
//
//    private void addToTable(Member member) {
//        //DefaultTableModel model = (DefaultTableModel) tbl_pInfo.getModel();
//
//        Object[] obj = new Object[6];
//
//        obj[0] = persoanlInfo.getName();
//        obj[1] = persoanlInfo.getContNum();
//        obj[2] = persoanlInfo.getEmail();
//        obj[3] = persoanlInfo.getDeptName();
//        obj[4] = persoanlInfo.getRegNum();
//        obj[5] = persoanlInfo.getSession();
//
//        //model.addRow(obj);
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMemberView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMemberView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMemberView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMemberView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMemberView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_srch;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> com_depts;
    private javax.swing.JComboBox<String> com_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_msgs;
    private javax.swing.JLabel lbl_msgsSrch;
    private javax.swing.JPanel pnl_sideBar;
    private javax.swing.JLabel sideBtn_member1;
    private javax.swing.JLabel sideBtn_member2;
    private javax.swing.JTextField t_cardNo;
    private javax.swing.JTextField t_cntNum;
    private javax.swing.JTextField t_crdNotoSrch;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_regNo;
    private javax.swing.JTextField t_session;
    // End of variables declaration//GEN-END:variables
}
