package view;

import controller.pojo.Manager;
import controller.pojo.Meal;
import controller.pojo.Member;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import model.dao.AssignedMonthsServices;
import model.dao.DeptNmaesServices;
import model.dao.MealDayAndDateServices;
import model.dao.MealDetailsServices;
import model.dao.MealHistoryServices;
import model.dao.MealManageService;
import model.dao.MemberServices;
import model.dao.MonthDetailsServices;
import model.dao.OffDaysServices;

public class MealDetailsView extends javax.swing.JFrame {

    /**
     * Creates new form PersonalInfo
     */
    MemberServices memberServices = new MemberServices();
    DeptNmaesServices deptNmaesServices = new DeptNmaesServices();
    MealManageService mealManageService = new MealManageService();
    MonthDetailsServices monthDetailsServices = new MonthDetailsServices();
    MealDayAndDateServices mealDayAndDateServices = new MealDayAndDateServices();
    MealHistoryServices mealHistoryServices = new MealHistoryServices();

    String monthName = "";
    String year = "";
    Manager manager = null;

    int day = mealDayAndDateServices.getDay();
    java.sql.Date meal_date = mealDayAndDateServices.getDate();

    int totalActiveCards = mealManageService.totalCards();
    int totalOffCards = mealManageService.totaloffMeals();
    int totalOnCards = totalActiveCards - totalOffCards;
    MealDetailsServices mealDetailsServices = new MealDetailsServices();

    double normalMealRate = 0;
    double fridayMealRate = 0;
    double feasrMealRate = 0;
    double actualExpense = 0;

    public MealDetailsView(Manager manager) {

        initComponents();
        monthName = manager.getMonthName();
        year = manager.getYear();
        this.manager = manager;

        normalMealRate = monthDetailsServices.getNormalMealRate(manager);
        fridayMealRate = monthDetailsServices.getFridayMealRate(manager);
        feasrMealRate = monthDetailsServices.getFeastMealRate(manager);

        lbl_title.setText("Month Name:" + manager.getMonthName() + " " + manager.getYear());

        this.setTitle("Meal Details");

        lbl_bg.setBackground(new Color(0, 0, 0, 0));
        t_spentExpense.setBackground(new Color(0, 0, 0, 0));
        txt_itemDetails.setBackground(new Color(0, 0, 0, 0));

        pnl_sideBar.setBackground(new Color(0, 0, 0, 100));

        lbl_mealDate.setText(meal_date.toString());
        lbl_totalMeals.setText(totalActiveCards + "");
        lbl_totalOnMeals.setText(totalOnCards + "");
        lbl_offMeals.setText(totalOffCards + "");
        actualExpense = normalMealRate * 2 * totalOnCards;
        lbl_actualExpense.setText(actualExpense + "");
    }

    private MealDetailsView() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void designTable(JTable tableName) {
        tableName.getTableHeader().setForeground(new Color(255, 255, 255));
        tableName.getTableHeader().setBackground(Color.BLACK);
        tableName.getTableHeader().setForeground(Color.black);

        ((DefaultTableCellRenderer) tableName.getDefaultRenderer(Object.class)).setOpaque(false);

        tableName.setBackground(new Color(0, 0, 0));
        //jScrollPane1.setBackground(new Color(0, 0, 0));
        //jScrollPane1.getViewport().setOpaque(false);
        tableName.setShowGrid(true);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableName.setDefaultRenderer(String.class, centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lbl_msgs = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        com_mealType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        t_spentExpense = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        lbl_title1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_actualExpense = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        lbl_balance = new javax.swing.JLabel();
        lbl_totalOnMeals = new javax.swing.JLabel();
        lbl_offMeals = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_itemDetails = new javax.swing.JTextArea();
        pnl_sideBar = new javax.swing.JPanel();
        sideBtn_addmmeber = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sideBtn_addMontlyExpensess = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sideBtn_addMealDetails = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sideBtn_collectExpense = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sideBtn_manageMeals = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_totalMeals = new javax.swing.JLabel();
        lbl_mealDate = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Personal Information");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 170, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 1020, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total On Meals");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 100, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 250, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Meal Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Off Meals");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 100, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 250, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Actual Expenses");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 110, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 250, 10));
        getContentPane().add(lbl_msgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 430, 140, 30));

        btn_save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("Save");
        btn_save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_save.setContentAreaFilled(false);
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 100, 40));

        com_mealType.setBackground(new java.awt.Color(255, 51, 51));
        com_mealType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        com_mealType.setForeground(new java.awt.Color(0, 102, 51));
        com_mealType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Friday", "Feast", "Friday & Feast" }));
        com_mealType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        com_mealType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                com_mealTypeItemStateChanged(evt);
            }
        });
        getContentPane().add(com_mealType, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 250, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Spent expense");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 100, 30));

        t_spentExpense.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_spentExpense.setForeground(new java.awt.Color(255, 255, 255));
        t_spentExpense.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_spentExpense.setBorder(null);
        t_spentExpense.setOpaque(false);
        t_spentExpense.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_spentExpenseKeyReleased(evt);
            }
        });
        getContentPane().add(t_spentExpense, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, 250, 30));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, 250, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Menu");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 70, 30));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 20, 450));

        lbl_title1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_title1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title1.setText("Meal Details");
        getContentPane().add(lbl_title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 280, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 70, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Meal");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 100, 30));

        lbl_actualExpense.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_actualExpense.setForeground(new java.awt.Color(255, 255, 255));
        lbl_actualExpense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_actualExpense, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 250, 30));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 250, 10));

        lbl_balance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_balance.setForeground(new java.awt.Color(255, 255, 255));
        lbl_balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 250, 30));

        lbl_totalOnMeals.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_totalOnMeals.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalOnMeals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_totalOnMeals, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 250, 30));

        lbl_offMeals.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_offMeals.setForeground(new java.awt.Color(255, 255, 255));
        lbl_offMeals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_offMeals, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 250, 30));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 250, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Balance");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 70, 30));

        txt_itemDetails.setColumns(20);
        txt_itemDetails.setRows(5);
        txt_itemDetails.setBorder(null);
        txt_itemDetails.setOpaque(false);
        jScrollPane1.setViewportView(txt_itemDetails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 280, 250, 130));

        pnl_sideBar.setBackground(new java.awt.Color(0, 0, 0));
        pnl_sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBtn_addmmeber.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_addmmeber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_addmmeber.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_addmmeber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_addmmeber.setText("Add Member");
        sideBtn_addmmeber.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_addmmeber.setOpaque(true);
        sideBtn_addmmeber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtn_addmmeberMouseClicked(evt);
            }
        });
        pnl_sideBar.add(sideBtn_addmmeber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 180, 40));

        jLabel13.setOpaque(true);
        pnl_sideBar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 10, 40));

        sideBtn_addMontlyExpensess.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_addMontlyExpensess.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_addMontlyExpensess.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_addMontlyExpensess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_addMontlyExpensess.setText("Preapre Month");
        sideBtn_addMontlyExpensess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_addMontlyExpensess.setOpaque(true);
        sideBtn_addMontlyExpensess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtn_addMontlyExpensessMouseClicked(evt);
            }
        });
        pnl_sideBar.add(sideBtn_addMontlyExpensess, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 180, 40));

        jLabel14.setOpaque(true);
        pnl_sideBar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 10, 40));

        sideBtn_addMealDetails.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_addMealDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_addMealDetails.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_addMealDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_addMealDetails.setText("Meal Details");
        sideBtn_addMealDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_addMealDetails.setOpaque(true);
        sideBtn_addMealDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtn_addMealDetailsMouseClicked(evt);
            }
        });
        pnl_sideBar.add(sideBtn_addMealDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 180, 40));

        jLabel15.setOpaque(true);
        pnl_sideBar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 10, 40));

        sideBtn_collectExpense.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_collectExpense.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_collectExpense.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_collectExpense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_collectExpense.setText("Collect Expense");
        sideBtn_collectExpense.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_collectExpense.setOpaque(true);
        sideBtn_collectExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtn_collectExpenseMouseClicked(evt);
            }
        });
        pnl_sideBar.add(sideBtn_collectExpense, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, 40));

        jLabel17.setOpaque(true);
        pnl_sideBar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 10, 40));

        sideBtn_manageMeals.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_manageMeals.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_manageMeals.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_manageMeals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_manageMeals.setText("Manage Meal");
        sideBtn_manageMeals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_manageMeals.setOpaque(true);
        sideBtn_manageMeals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtn_manageMealsMouseClicked(evt);
            }
        });
        pnl_sideBar.add(sideBtn_manageMeals, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 40));

        jLabel18.setOpaque(true);
        pnl_sideBar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 10, 40));

        getContentPane().add(pnl_sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 650));

        lbl_totalMeals.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_totalMeals.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalMeals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_totalMeals, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 250, 30));

        lbl_mealDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_mealDate.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mealDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_mealDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 250, 30));

        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 250, 10));

        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 210, 250, 10));

        lbl_bg.setBackground(new java.awt.Color(0, 102, 102));
        lbl_bg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_bg.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bg.setOpaque(true);
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        double spentExpense = 0;
        try {
            if (spentExpense < 0) {
                lbl_msgs.setText("You have entered negative number");
                lbl_msgs.setForeground(Color.red);
            } else {
                spentExpense = Integer.parseInt(t_spentExpense.getText().trim());
            }
        } catch (NumberFormatException e) {
            lbl_msgs.setText("Enter only number");
            lbl_msgs.setForeground(Color.red);
        }

        String menu = txt_itemDetails.getText().trim();

        if (spentExpense == 0) {
            lbl_msgs.setText("Enter Spent expense");
            lbl_msgs.setForeground(Color.red);
            return;
        }

        if (menu.isEmpty()) {
            lbl_msgs.setText("Enter Menu Details");
            lbl_msgs.setForeground(Color.red);
            return;
        } else {
            int totalActiveMember = Integer.parseInt(lbl_totalMeals.getText().trim());
            int totalOnMeals = Integer.parseInt(lbl_totalOnMeals.getText().trim());
            int totalOffMeal = Integer.parseInt(lbl_offMeals.getText().trim());
            String mealType = com_mealType.getSelectedItem().toString();
            double actual_expensess = Double.parseDouble(lbl_actualExpense.getText().trim());
            double balance = actual_expensess - spentExpense;
            
            Meal meal = new Meal(meal_date, totalActiveMember, totalOnMeals, totalOffMeal, mealType, actual_expensess, spentExpense, balance, menu);

            if (mealDetailsServices.updateMealDetails(meal, manager) > 0) {
                lbl_msgs.setText("Wait....");
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MealDetailsView.class.getName()).log(Level.SEVERE, null, ex);
                }
                List<Integer> cardsToUpdateMeal = mealManageService.cardList();
                for (int cardNo : cardsToUpdateMeal) {
                    mealHistoryServices.updateStatusForNextMeal(cardNo, meal_date, manager);
                }
                mealDayAndDateServices.deleteFromDayWithDate(day);
                mealManageService.prepareCMSTable();
                lbl_msgs.setText("Details saved");
            }
        }


    }//GEN-LAST:event_btn_saveActionPerformed

    private void sideBtn_addmmeberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtn_addmmeberMouseClicked
        // TODO add your handling code here:
        new Addmember().setVisible(true);
    }//GEN-LAST:event_sideBtn_addmmeberMouseClicked

    private void sideBtn_addMontlyExpensessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtn_addMontlyExpensessMouseClicked
        // TODO add your handling code here:
        new PrepareMonthView(manager).setVisible(true);
    }//GEN-LAST:event_sideBtn_addMontlyExpensessMouseClicked

    private void sideBtn_addMealDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtn_addMealDetailsMouseClicked
        // TODO add your handling code here:
        new MealDetailsView(manager).setVisible(true);
    }//GEN-LAST:event_sideBtn_addMealDetailsMouseClicked

    private void sideBtn_collectExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtn_collectExpenseMouseClicked
        // TODO add your handling code here:
        new MonthlyExpenseView(manager).setVisible(true);
    }//GEN-LAST:event_sideBtn_collectExpenseMouseClicked

    private void sideBtn_manageMealsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtn_manageMealsMouseClicked
        // TODO add your handling code here:
        new StartMealView(manager).setVisible(true);
    }//GEN-LAST:event_sideBtn_manageMealsMouseClicked

    private void com_mealTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_com_mealTypeItemStateChanged
        // TODO add your handling code here:
        String mealType = com_mealType.getSelectedItem().toString();
        actualExpense = 0;
        if (mealType.equals("Normal")) {

            actualExpense = totalOnCards * 2 * normalMealRate;
            lbl_actualExpense.setText(actualExpense + "");

        } else if (mealType.equals("Friday")) {

            actualExpense = totalOnCards * fridayMealRate + totalOnCards * normalMealRate;
            lbl_actualExpense.setText(actualExpense + "");

        } else if (mealType.equals("Feast")) {
            actualExpense = totalOnCards * 2 * normalMealRate + totalOnCards * feasrMealRate;
            lbl_actualExpense.setText(actualExpense + "");
        } else {
            double mealRate = (totalOnCards * feasrMealRate) + (totalOnCards * fridayMealRate) + (totalOnCards * normalMealRate);
            lbl_actualExpense.setText(mealRate + "");
        }
    }//GEN-LAST:event_com_mealTypeItemStateChanged

    private void t_spentExpenseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_spentExpenseKeyReleased
        // TODO add your handling code here:
        double spentExpense = 0;
        try {
            actualExpense = Double.parseDouble(lbl_actualExpense.getText());
            spentExpense = Double.parseDouble(t_spentExpense.getText().trim());
            if (spentExpense < 0) {
                lbl_balance.setText("Spent expense can not be negative");
            } else {
                lbl_balance.setText((actualExpense - spentExpense) + "");
            }

        } catch (NumberFormatException e) {
            lbl_msgs.setText("Enter valid card No");
            lbl_msgs.setForeground(Color.red);
        }
    }//GEN-LAST:event_t_spentExpenseKeyReleased
//
//    private void addToTable(Member member) {
//        //DefaultTableModel model = (DefaultTableModel) tbl_pInfo.getModel();
//
//        Object[] obj = new Object[6];
//
//        obj[0] = persoanlInfo.getName();
//        obj[1] = persoanlInfo.getContNum();
//        obj[2] = persoanlInfo.getEmail();
//        obj[3] = persoanlInfo.getDeptName();
//        obj[4] = persoanlInfo.getRegNum();
//        obj[5] = persoanlInfo.getSession();
//
//        //model.addRow(obj);
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MealDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MealDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MealDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MealDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MealDetailsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> com_mealType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbl_actualExpense;
    private javax.swing.JLabel lbl_balance;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_mealDate;
    private javax.swing.JLabel lbl_msgs;
    private javax.swing.JLabel lbl_offMeals;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel lbl_totalMeals;
    private javax.swing.JLabel lbl_totalOnMeals;
    private javax.swing.JPanel pnl_sideBar;
    private javax.swing.JLabel sideBtn_addMealDetails;
    private javax.swing.JLabel sideBtn_addMontlyExpensess;
    private javax.swing.JLabel sideBtn_addmmeber;
    private javax.swing.JLabel sideBtn_collectExpense;
    private javax.swing.JLabel sideBtn_manageMeals;
    private javax.swing.JTextField t_spentExpense;
    private javax.swing.JTextArea txt_itemDetails;
    // End of variables declaration//GEN-END:variables
}
