package view;

import controller.pojo.Summary;
import controller.pojo.Manager;
import controller.pojo.Member;
import controller.pojo.MonthlyExpense;
import java.awt.Color;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import model.dao.DeptNmaesServices;
import model.dao.MealHistoryServices;
import model.dao.SummaryService;
import model.dao.MemberServices;
import model.dao.MonthDetailsServices;
import model.dao.MonthlyExpensessServices;

public class MonthlyExpenseView extends javax.swing.JFrame {

    /**
     * Creates new form PersonalInfo
     */
    MemberServices memberServices = new MemberServices();
    DeptNmaesServices deptNmaesServices = new DeptNmaesServices();
    SummaryService lastMonthSummaryService = new SummaryService();
    MonthDetailsServices monthDetailsServices = new MonthDetailsServices();
    MonthlyExpensessServices monthlyExpensessServices = new MonthlyExpensessServices();
    MealHistoryServices mealHistoryServices = new MealHistoryServices();
    SummaryService summaryService = new SummaryService();

    Member member = null;
    Summary lastMonthSummary = null;

    ArrayList<String> deptNames = (ArrayList<String>) deptNmaesServices.getDepartmentList();
    String monthName = "";
    String year = "";
    Manager manager = null;

    public MonthlyExpenseView(Manager manager) {

        initComponents();
        monthName = manager.getMonthName();
        year = manager.getYear();
        this.manager = manager;

        LogingPage logingPage = new LogingPage();
        lbl_title.setText("Month Name:" + manager.getMonthName() + " " + manager.getYear());
        this.setTitle("Registrar Memebr");
        lbl_bg.setBackground(new Color(0, 0, 0, 0));
        t_cardNo.setBackground(new Color(0, 0, 0, 0));
        pnl_sideBar.setBackground(new Color(0, 0, 0, 100));

    }

    private MonthlyExpenseView() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void designTable(JTable tableName) {
        tableName.getTableHeader().setForeground(new Color(255, 255, 255));
        tableName.getTableHeader().setBackground(Color.BLACK);
        tableName.getTableHeader().setForeground(Color.black);

        ((DefaultTableCellRenderer) tableName.getDefaultRenderer(Object.class)).setOpaque(false);

        tableName.setBackground(new Color(0, 0, 0));
        //jScrollPane1.setBackground(new Color(0, 0, 0));
        //jScrollPane1.getViewport().setOpaque(false);
        tableName.setShowGrid(true);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableName.setDefaultRenderer(String.class, centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_sideBar = new javax.swing.JPanel();
        sideBtn_addmmeber = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sideBtn_addMontlyExpensess = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sideBtn_addMealDetails = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sideBtn_submitMeal = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lbl_msgs = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        t_cardNo = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        drpDown_mealDetails = new javax.swing.JPanel();
        btn_addMealDetails = new javax.swing.JLabel();
        btn_editMealDetails = new javax.swing.JLabel();
        btn_removeMealDetails = new javax.swing.JLabel();
        drpDown_member = new javax.swing.JPanel();
        btn_addMember = new javax.swing.JLabel();
        btn_editMember = new javax.swing.JLabel();
        btn_removeMember = new javax.swing.JLabel();
        lbl_title1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_needToPay = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        lbl_stName = new javax.swing.JLabel();
        lbl_deptName = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        btn_srch = new javax.swing.JButton();
        lbl_msgsSrchh = new javax.swing.JLabel();
        lbl_title2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_monthlyExpenseTitle = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        lbl_session = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        lbl_bumping = new javax.swing.JLabel();
        lbl_thisMonthExpens = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_sideBar.setBackground(new java.awt.Color(0, 0, 0));
        pnl_sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBtn_addmmeber.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_addmmeber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_addmmeber.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_addmmeber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_addmmeber.setText("Add Member");
        sideBtn_addmmeber.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_addmmeber.setOpaque(true);
        sideBtn_addmmeber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtn_addmmeberMouseClicked(evt);
            }
        });
        pnl_sideBar.add(sideBtn_addmmeber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 180, 40));

        jLabel13.setOpaque(true);
        pnl_sideBar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 10, 40));

        sideBtn_addMontlyExpensess.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_addMontlyExpensess.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_addMontlyExpensess.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_addMontlyExpensess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_addMontlyExpensess.setText("Preapre Month");
        sideBtn_addMontlyExpensess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_addMontlyExpensess.setOpaque(true);
        sideBtn_addMontlyExpensess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtn_addMontlyExpensessMouseClicked(evt);
            }
        });
        pnl_sideBar.add(sideBtn_addMontlyExpensess, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 40));

        jLabel14.setOpaque(true);
        pnl_sideBar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 10, 40));

        sideBtn_addMealDetails.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_addMealDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_addMealDetails.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_addMealDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_addMealDetails.setText("Meal Details");
        sideBtn_addMealDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_addMealDetails.setOpaque(true);
        sideBtn_addMealDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtn_addMealDetailsMouseClicked(evt);
            }
        });
        pnl_sideBar.add(sideBtn_addMealDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 180, 40));

        jLabel15.setOpaque(true);
        pnl_sideBar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 10, 40));

        sideBtn_submitMeal.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_submitMeal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_submitMeal.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_submitMeal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_submitMeal.setText("Submit Meals");
        sideBtn_submitMeal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_submitMeal.setOpaque(true);
        sideBtn_submitMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtn_submitMealMouseClicked(evt);
            }
        });
        pnl_sideBar.add(sideBtn_submitMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 40));

        jLabel16.setOpaque(true);
        pnl_sideBar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 10, 40));

        getContentPane().add(pnl_sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 650));

        lbl_title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Personal Information");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 170, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 1020, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 100, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, 250, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 100, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, 250, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Last Month Bumping");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 130, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, 250, 10));
        getContentPane().add(lbl_msgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 140, 30));

        btn_save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("Save");
        btn_save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_save.setContentAreaFilled(false);
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 530, 100, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("This Month Expense");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, -1, 30));

        t_cardNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_cardNo.setForeground(new java.awt.Color(255, 255, 255));
        t_cardNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_cardNo.setBorder(null);
        t_cardNo.setOpaque(false);
        getContentPane().add(t_cardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 250, 30));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 250, 10));

        btn_addMealDetails.setBackground(new java.awt.Color(51, 0, 153));
        btn_addMealDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_addMealDetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_addMealDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_addMealDetails.setText("Add Meal Details");
        btn_addMealDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addMealDetails.setOpaque(true);
        btn_addMealDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addMealDetailsMouseClicked(evt);
            }
        });

        btn_editMealDetails.setBackground(new java.awt.Color(51, 0, 153));
        btn_editMealDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_editMealDetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_editMealDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_editMealDetails.setText("Edit Meal Details");
        btn_editMealDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editMealDetails.setOpaque(true);

        btn_removeMealDetails.setBackground(new java.awt.Color(51, 0, 153));
        btn_removeMealDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_removeMealDetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_removeMealDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_removeMealDetails.setText("Remove a Meal");
        btn_removeMealDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_removeMealDetails.setOpaque(true);

        javax.swing.GroupLayout drpDown_mealDetailsLayout = new javax.swing.GroupLayout(drpDown_mealDetails);
        drpDown_mealDetails.setLayout(drpDown_mealDetailsLayout);
        drpDown_mealDetailsLayout.setHorizontalGroup(
            drpDown_mealDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drpDown_mealDetailsLayout.createSequentialGroup()
                .addGroup(drpDown_mealDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addMealDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editMealDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_removeMealDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        drpDown_mealDetailsLayout.setVerticalGroup(
            drpDown_mealDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drpDown_mealDetailsLayout.createSequentialGroup()
                .addComponent(btn_addMealDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_editMealDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_removeMealDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(drpDown_mealDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 130, 130));

        btn_addMember.setBackground(new java.awt.Color(51, 0, 153));
        btn_addMember.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_addMember.setForeground(new java.awt.Color(255, 255, 255));
        btn_addMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_addMember.setText("Add Member");
        btn_addMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addMember.setOpaque(true);

        btn_editMember.setBackground(new java.awt.Color(51, 0, 153));
        btn_editMember.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_editMember.setForeground(new java.awt.Color(255, 255, 255));
        btn_editMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_editMember.setText("Edit Info");
        btn_editMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editMember.setOpaque(true);

        btn_removeMember.setBackground(new java.awt.Color(51, 0, 153));
        btn_removeMember.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_removeMember.setForeground(new java.awt.Color(255, 255, 255));
        btn_removeMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_removeMember.setText("Remove Member");
        btn_removeMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_removeMember.setOpaque(true);

        javax.swing.GroupLayout drpDown_memberLayout = new javax.swing.GroupLayout(drpDown_member);
        drpDown_member.setLayout(drpDown_memberLayout);
        drpDown_memberLayout.setHorizontalGroup(
            drpDown_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drpDown_memberLayout.createSequentialGroup()
                .addGroup(drpDown_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addMember, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editMember, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_removeMember, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        drpDown_memberLayout.setVerticalGroup(
            drpDown_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drpDown_memberLayout.createSequentialGroup()
                .addComponent(btn_addMember, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_editMember, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_removeMember, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(drpDown_member, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 130, 180));

        lbl_title1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_title1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title1.setText("Monthly Expenses Collection");
        getContentPane().add(lbl_title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 280, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter Card No.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 100, 30));

        lbl_needToPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_needToPay.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_needToPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 430, 250, 30));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 250, 10));

        lbl_stName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_stName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_stName, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, 250, 30));

        lbl_deptName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_deptName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_deptName, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 160, 250, 30));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, 250, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Need To Pay");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 90, 30));

        btn_srch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_srch.setForeground(new java.awt.Color(255, 255, 255));
        btn_srch.setText("Search");
        btn_srch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_srch.setContentAreaFilled(false);
        btn_srch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_srchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_srch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 100, 40));
        getContentPane().add(lbl_msgsSrchh, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 140, 30));

        lbl_title2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_title2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title2.setText("Member Info.");
        getContentPane().add(lbl_title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 490, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 490, 10));

        lbl_monthlyExpenseTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_monthlyExpenseTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_monthlyExpenseTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_monthlyExpenseTitle.setText("Monthly Expense");
        getContentPane().add(lbl_monthlyExpenseTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 490, 20));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 490, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Session");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 100, 30));

        lbl_session.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_session.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_session, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, 250, 30));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 250, 10));

        lbl_bumping.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_bumping.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_bumping, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, 250, 30));

        lbl_thisMonthExpens.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_thisMonthExpens.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_thisMonthExpens, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 250, 30));

        lbl_bg.setBackground(new java.awt.Color(0, 102, 102));
        lbl_bg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_bg.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bg.setOpaque(true);
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int cardNo = 0;
    
    //List<Integer> cardListInMealHistoryTable = mealHistoryServices.getCardList(manager);
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:

        if (member == null && lastMonthSummary == null) {
            lbl_msgs.setText("Perform search first");
            lbl_msgs.setForeground(Color.red);
        } else {
            double needToPay = Double.parseDouble(lbl_needToPay.getText().trim());
            MonthlyExpense monthlyExpense = new MonthlyExpense(cardNo, lastMonthSummary.getBumping(), needToPay, new Date(System.currentTimeMillis()));
            
            
            monthlyExpensessServices.saveMonthlyExpense(monthlyExpense,manager);
            
            
            lbl_msgs.setText(cardNo + " paid monthly expense");
            lbl_msgs.setForeground(Color.red);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void sideBtn_addmmeberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtn_addmmeberMouseClicked
        // TODO add your handling code here:
        new Addmember().setVisible(true);
    }//GEN-LAST:event_sideBtn_addmmeberMouseClicked

    private void sideBtn_addMontlyExpensessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtn_addMontlyExpensessMouseClicked
        // TODO add your handling code here:
        new PrepareMonthView(manager).setVisible(true);
    }//GEN-LAST:event_sideBtn_addMontlyExpensessMouseClicked

    private void sideBtn_addMealDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtn_addMealDetailsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sideBtn_addMealDetailsMouseClicked

    private void sideBtn_submitMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtn_submitMealMouseClicked
        // TODO add your handling code here:
        new SubmitMeal(manager).setVisible(true);
    }//GEN-LAST:event_sideBtn_submitMealMouseClicked

    private void btn_addMealDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMealDetailsMouseClicked
        // TODO add your handling code here:
        new AddMealDetailsView(manager).setVisible(true);
    }//GEN-LAST:event_btn_addMealDetailsMouseClicked

    private void btn_srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_srchActionPerformed
        // TODO add your handling code here:
        try {
            cardNo = Integer.parseInt(t_cardNo.getText().trim());
        } catch (NumberFormatException e) {
            lbl_msgsSrchh.setText("Inter valid card no.");
            lbl_msgsSrchh.setForeground(Color.red);
        }
        member = memberServices.getMemberByCardNo(cardNo);
        lbl_stName.setText(member.getName());
        lbl_deptName.setText(member.getDeptName());
        lbl_session.setText(member.getSession());

        lastMonthSummary = lastMonthSummaryService.getLastMonthSummaryByCardNo(cardNo);
        double thisMonthExpense = monthDetailsServices.getThisMonthExpense(manager);
        lbl_thisMonthExpens.setText(thisMonthExpense + "");
        lbl_bumping.setText(lastMonthSummary.getBumping() + "");
        lbl_needToPay.setText((thisMonthExpense - lastMonthSummary.getBumping()) + "");

    }//GEN-LAST:event_btn_srchActionPerformed
//
//    private void addToTable(Member member) {
//        //DefaultTableModel model = (DefaultTableModel) tbl_pInfo.getModel();
//
//        Object[] obj = new Object[6];
//
//        obj[0] = persoanlInfo.getName();
//        obj[1] = persoanlInfo.getContNum();
//        obj[2] = persoanlInfo.getEmail();
//        obj[3] = persoanlInfo.getDeptName();
//        obj[4] = persoanlInfo.getRegNum();
//        obj[5] = persoanlInfo.getSession();
//
//        //model.addRow(obj);
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlyExpenseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlyExpenseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlyExpenseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlyExpenseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthlyExpenseView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_addMealDetails;
    private javax.swing.JLabel btn_addMember;
    private javax.swing.JLabel btn_editMealDetails;
    private javax.swing.JLabel btn_editMember;
    private javax.swing.JLabel btn_removeMealDetails;
    private javax.swing.JLabel btn_removeMember;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_srch;
    private javax.swing.JPanel drpDown_mealDetails;
    private javax.swing.JPanel drpDown_member;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_bumping;
    private javax.swing.JLabel lbl_deptName;
    private javax.swing.JLabel lbl_monthlyExpenseTitle;
    private javax.swing.JLabel lbl_msgs;
    private javax.swing.JLabel lbl_msgsSrchh;
    private javax.swing.JLabel lbl_needToPay;
    private javax.swing.JLabel lbl_session;
    private javax.swing.JLabel lbl_stName;
    private javax.swing.JLabel lbl_thisMonthExpens;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JPanel pnl_sideBar;
    private javax.swing.JLabel sideBtn_addMealDetails;
    private javax.swing.JLabel sideBtn_addMontlyExpensess;
    private javax.swing.JLabel sideBtn_addmmeber;
    private javax.swing.JLabel sideBtn_submitMeal;
    private javax.swing.JTextField t_cardNo;
    // End of variables declaration//GEN-END:variables
}
