/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.pojo.Manager;
import java.awt.Color;
import java.sql.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.dao.DeptNmaesServices;
import model.dao.MealDayAndDateServices;
import model.dao.MealHistoryServices;
import model.dao.MealManageService;
import model.dao.MealStopService;
import model.dao.MemberServices;
import model.dao.MonthDetailsServices;

/**
 *
 * @author OLEE
 */
public class StartMealView extends javax.swing.JFrame {

    /**
     * Creates new form PersonalInfo
     */
    MemberServices memberServices = new MemberServices();
    DeptNmaesServices deptNmaesServices = new DeptNmaesServices();
    MealManageService mealManageService = new MealManageService();
    MealStopService mealStopService = new MealStopService();
    MealHistoryServices mealHistoryServices = new MealHistoryServices();
    MonthDetailsServices monthDetailsServices = new MonthDetailsServices();

    String monthName = "";
    String year = "";
    Manager manager = null;
    List<String> dateList = null;
    static int day = MealDayAndDateServices.getDay();
    static Date meal_date = MealDayAndDateServices.getDate();

    public StartMealView(Manager manager) {

        initComponents();
        monthName = manager.getMonthName();
        year = manager.getYear();
        this.manager = manager;

        lbl_day.setText("Day " + day + "");
        lbl_date.setText("Date " + meal_date.toString());

        lbl_dayInStartMeal.setText("Day " + day + "");
        lbl_dateInstatMeal.setText("Date " + meal_date.toString());

        dateList = monthDetailsServices.getDateList(manager);
        lbl_title.setText("Month Name:" + manager.getMonthName() + " " + manager.getYear());
        this.setTitle("Registrar Memebr");

        t_cardNoForStart.setBackground(new Color(0, 0, 0, 0));
        pnl_sideBar.setBackground(new Color(0, 0, 0, 100));

        designTable(tbl_started);

    }

    private StartMealView() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void designTable(JTable tableName) {
        tableName.getTableHeader().setForeground(new Color(255, 255, 255));
        tableName.getTableHeader().setBackground(Color.BLACK);
        tableName.getTableHeader().setForeground(Color.black);

        ((DefaultTableCellRenderer) tableName.getDefaultRenderer(Object.class)).setOpaque(false);

        tableName.setBackground(new Color(0, 0, 0));
        //jScrollPane1.setBackground(new Color(0, 0, 0));
        //jScrollPane1.getViewport().setOpaque(false);
        tableName.setShowGrid(true);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableName.setDefaultRenderer(String.class, centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        lbl_title1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_start = new javax.swing.JButton();
        lbl_msgsStart = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        t_cardNoForStart = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbl_startedToday = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        lbl_dateInstatMeal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_started = new javax.swing.JTable();
        sideBtn_next = new javax.swing.JLabel();
        pnl_sideBar = new javax.swing.JPanel();
        sideBtn_addMeal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sideBtn_startMeal = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_dayInStartMeal = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();
        pnl_selectType = new javax.swing.JPanel();
        btn_next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_day = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Month Information");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 170, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 1020, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Start Meal");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 70, 30));

        lbl_title1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_title1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title1.setText("Start Meal");
        getContentPane().add(lbl_title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 280, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 420, 10));

        btn_start.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_start.setForeground(new java.awt.Color(255, 255, 255));
        btn_start.setText("Start");
        btn_start.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_start.setContentAreaFilled(false);
        btn_start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        getContentPane().add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 100, 40));
        getContentPane().add(lbl_msgsStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 250, 40));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 250, 10));

        t_cardNoForStart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_cardNoForStart.setForeground(new java.awt.Color(255, 255, 255));
        t_cardNoForStart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_cardNoForStart.setBorder(null);
        t_cardNoForStart.setOpaque(false);
        getContentPane().add(t_cardNoForStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 250, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Card No");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 70, 30));

        lbl_startedToday.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_startedToday.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_startedToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 80, 30));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 420, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cards Stared Meal Today");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 160, 170, 30));

        lbl_dateInstatMeal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_dateInstatMeal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dateInstatMeal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dateInstatMeal.setText("Date");
        getContentPane().add(lbl_dateInstatMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 120, 30));

        tbl_started.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_started.setForeground(new java.awt.Color(255, 255, 255));
        tbl_started.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Card No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_started.setRowHeight(30);
        jScrollPane1.setViewportView(tbl_started);
        if (tbl_started.getColumnModel().getColumnCount() > 0) {
            tbl_started.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, 100, 220));

        sideBtn_next.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_next.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_next.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_next.setText("Next >>");
        sideBtn_next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_next.setOpaque(true);
        sideBtn_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtn_nextMouseClicked(evt);
            }
        });
        getContentPane().add(sideBtn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 180, 40));

        pnl_sideBar.setBackground(new java.awt.Color(0, 0, 0));
        pnl_sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBtn_addMeal.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_addMeal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_addMeal.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_addMeal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_addMeal.setText("Add Meal");
        sideBtn_addMeal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_addMeal.setOpaque(true);
        sideBtn_addMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtn_addMealMouseClicked(evt);
            }
        });
        pnl_sideBar.add(sideBtn_addMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 40));

        jLabel14.setOpaque(true);
        pnl_sideBar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 10, 40));

        jLabel15.setOpaque(true);
        pnl_sideBar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 10, 40));

        sideBtn_startMeal.setBackground(new java.awt.Color(51, 0, 153));
        sideBtn_startMeal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sideBtn_startMeal.setForeground(new java.awt.Color(255, 255, 255));
        sideBtn_startMeal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtn_startMeal.setText("Start Meal");
        sideBtn_startMeal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_startMeal.setOpaque(true);
        sideBtn_startMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtn_startMealMouseClicked(evt);
            }
        });
        pnl_sideBar.add(sideBtn_startMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 40));

        jLabel16.setOpaque(true);
        pnl_sideBar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 10, 40));

        getContentPane().add(pnl_sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 650));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Total:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, 60, 30));

        lbl_dayInStartMeal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_dayInStartMeal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dayInStartMeal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dayInStartMeal.setText("Day");
        getContentPane().add(lbl_dayInStartMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 60, 30));

        lbl_bg.setBackground(new java.awt.Color(0, 102, 102));
        lbl_bg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_bg.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bg.setOpaque(true);
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 650));

        pnl_selectType.setBackground(new java.awt.Color(51, 51, 51));

        btn_next.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_next.setForeground(new java.awt.Color(255, 255, 255));
        btn_next.setText("Next");
        btn_next.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_next.setContentAreaFilled(false);
        btn_next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carefully Complete All Steps");

        lbl_day.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_day.setForeground(new java.awt.Color(255, 102, 102));
        lbl_day.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_day.setText("Day");

        lbl_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(255, 102, 102));
        lbl_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_date.setText("Day");

        javax.swing.GroupLayout pnl_selectTypeLayout = new javax.swing.GroupLayout(pnl_selectType);
        pnl_selectType.setLayout(pnl_selectTypeLayout);
        pnl_selectTypeLayout.setHorizontalGroup(
            pnl_selectTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_selectTypeLayout.createSequentialGroup()
                .addGap(0, 396, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(404, 404, 404))
            .addGroup(pnl_selectTypeLayout.createSequentialGroup()
                .addGroup(pnl_selectTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_selectTypeLayout.createSequentialGroup()
                        .addGap(477, 477, 477)
                        .addGroup(pnl_selectTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_day, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_selectTypeLayout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_selectTypeLayout.setVerticalGroup(
            pnl_selectTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_selectTypeLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_day, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(pnl_selectType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1120, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        int cardNo = 0;
        int count = 0;
        try {
            cardNo = Integer.parseInt(t_cardNoForStart.getText().trim());
        } catch (NumberFormatException e) {
            lbl_msgsStart.setText("Enter only digit");
            lbl_msgsStart.setForeground(Color.red);
        }

        if (cardNo == 0 || cardNo < 0) {
            lbl_msgsStart.setText("Enter valid");
            lbl_msgsStart.setForeground(Color.red);
        } else {
            if (mealStopService.getCardList().contains(cardNo)) {
                mealStopService.removeFromOffCardList(cardNo);
                count++;
                addToTable(cardNo, tbl_started);
                lbl_startedToday.setText(count + "");
                lbl_msgsStart.setText("Started Meal For " + cardNo);
                lbl_msgsStart.setForeground(Color.GREEN);

            } else {
                lbl_msgsStart.setText("Meal was not stoped for " + cardNo);
                lbl_msgsStart.setForeground(Color.red);
            }

        }
    }//GEN-LAST:event_btn_startActionPerformed

    private void sideBtn_addMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtn_addMealMouseClicked
        // TODO add your handling code here:
        new AddMealView(manager).setVisible(true);
    }//GEN-LAST:event_sideBtn_addMealMouseClicked


    private void sideBtn_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtn_nextMouseClicked
        // TODO add your handling code here:
        Date toDayDate = null;
        if (meal_date == null) {
            lbl_msgsStart.setText("Select date");
            return;
        } else {
            toDayDate = new java.sql.Date(meal_date.getTime());
            if (dateList.contains(mealHistoryServices.dateFormate(toDayDate))) {
                toDayDate = new java.sql.Date(meal_date.getTime() - 86400000);
                mealStopService.removeAccordingToLastDate(meal_date);
                new StopMealView(manager).setVisible(true);
            } else {
                lbl_msgsStart.setText("Keep selected this meal date");
                lbl_msgsStart.setForeground(Color.red);
            }
        }


    }//GEN-LAST:event_sideBtn_nextMouseClicked


    private void sideBtn_startMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtn_startMealMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sideBtn_startMealMouseClicked

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        mealManageService.prepareCMSTable();
        pnl_selectType.setVisible(false);
    }//GEN-LAST:event_btn_nextActionPerformed
    private void addToTable(int cardNo, JTable tbl_name) {
        DefaultTableModel model = (DefaultTableModel) tbl_name.getModel();

        Object[] obj = new Object[1];

        obj[0] = cardNo + "";
        model.addRow(obj);
    }

//    private void addToTable(Member member) {
//        //DefaultTableModel model = (DefaultTableModel) tbl_pInfo.getModel();
//
//        Object[] obj = new Object[6];
//
//        obj[0] = persoanlInfo.getName();
//        obj[1] = persoanlInfo.getContNum();
//        obj[2] = persoanlInfo.getEmail();
//        obj[3] = persoanlInfo.getDeptName();
//        obj[4] = persoanlInfo.getRegNum();
//        obj[5] = persoanlInfo.getSession();
//
//        //model.addRow(obj);
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMealView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMealView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMealView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMealView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMealView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_dateInstatMeal;
    private javax.swing.JLabel lbl_day;
    private javax.swing.JLabel lbl_dayInStartMeal;
    private javax.swing.JLabel lbl_msgsStart;
    private javax.swing.JLabel lbl_startedToday;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JPanel pnl_selectType;
    private javax.swing.JPanel pnl_sideBar;
    private javax.swing.JLabel sideBtn_addMeal;
    private javax.swing.JLabel sideBtn_next;
    private javax.swing.JLabel sideBtn_startMeal;
    private javax.swing.JTextField t_cardNoForStart;
    private javax.swing.JTable tbl_started;
    // End of variables declaration//GEN-END:variables
}
