/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;

/**
 *
 * @author ccsl-pc
 */
public class AnalysisView extends javax.swing.JFrame {

    /**
     * Creates new form SlaeHistoryView
     */
    public AnalysisView() {
        initComponents();
        setLocationRelativeTo(null);
        pnl_header.setBackground(new Color(0,0,0,180));
        pnl_sideBar.setBackground(new Color(0,0,0,180));
        pnl_body.setBackground(new Color(0,0,0,150));
        sideBtn_revenue.setBackground(new Color(0,0,0,50));
        sideBtn_saleHistory.setBackground(new Color(0,0,0,50));
        sideBtn_purchaseHistory.setBackground(new Color(0,0,0,50));
        //sidebtn_home.setBackground(new Color(0,0,0,180));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_header = new javax.swing.JPanel();
        mainMenu_home = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mainMenu_purchase = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        mainMenu_sale = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        mainMenu_analysis = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnl_sideBar = new javax.swing.JPanel();
        sideBtn_revenue = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sideBtn_saleHistory = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sideBtn_purchaseHistory = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnl_body = new javax.swing.JPanel();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        pnl_header.setBackground(new java.awt.Color(0, 51, 51));
        pnl_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainMenu_home.setBackground(new java.awt.Color(102, 102, 102));
        mainMenu_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainMenu_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Home");
        mainMenu_home.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        pnl_header.add(mainMenu_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, 35));

        mainMenu_purchase.setBackground(new java.awt.Color(102, 102, 102));
        mainMenu_purchase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainMenu_purchase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Purchase");
        mainMenu_purchase.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        pnl_header.add(mainMenu_purchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, 35));

        lbl_exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit.setText("Exit");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });
        pnl_header.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1229, 10, 30, -1));

        mainMenu_sale.setBackground(new java.awt.Color(102, 102, 102));
        mainMenu_sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainMenu_sale.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Analysis");
        mainMenu_sale.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        pnl_header.add(mainMenu_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, 35));

        mainMenu_analysis.setBackground(new java.awt.Color(102, 102, 102));
        mainMenu_analysis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainMenu_analysis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sell");
        mainMenu_analysis.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        pnl_header.add(mainMenu_analysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, 35));

        jPanel1.add(pnl_header);
        pnl_header.setBounds(0, 0, 1290, 100);

        pnl_sideBar.setBackground(new java.awt.Color(0, 51, 51));
        pnl_sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBtn_revenue.setBackground(new java.awt.Color(102, 102, 102));
        sideBtn_revenue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_revenue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        sideBtn_revenue.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Revenue");
        sideBtn_revenue.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 5, 190, 30));

        pnl_sideBar.add(sideBtn_revenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        sideBtn_saleHistory.setBackground(new java.awt.Color(102, 102, 102));
        sideBtn_saleHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_saleHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        sideBtn_saleHistory.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sale History");
        sideBtn_saleHistory.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 40));

        pnl_sideBar.add(sideBtn_saleHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, -1));

        sideBtn_purchaseHistory.setBackground(new java.awt.Color(102, 102, 102));
        sideBtn_purchaseHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtn_purchaseHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        sideBtn_purchaseHistory.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Purchase History");
        sideBtn_purchaseHistory.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 40));

        pnl_sideBar.add(sideBtn_purchaseHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jPanel1.add(pnl_sideBar);
        pnl_sideBar.setBounds(0, 100, 200, 550);

        pnl_body.setForeground(new java.awt.Color(255, 255, 255));
        pnl_body.setLayout(null);
        jPanel1.add(pnl_body);
        pnl_body.setBounds(200, 100, 1080, 550);

        lbl_bg.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.add(lbl_bg);
        lbl_bg.setBounds(0, 0, 1280, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1275, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbl_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalysisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalysisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalysisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalysisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalysisView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JPanel mainMenu_analysis;
    private javax.swing.JPanel mainMenu_home;
    private javax.swing.JPanel mainMenu_purchase;
    private javax.swing.JPanel mainMenu_sale;
    private javax.swing.JPanel pnl_body;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_sideBar;
    private javax.swing.JPanel sideBtn_purchaseHistory;
    private javax.swing.JPanel sideBtn_revenue;
    private javax.swing.JPanel sideBtn_saleHistory;
    // End of variables declaration//GEN-END:variables
}
