/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import daoImpl.RoleServices;
import daoImpl.UserDBServices;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import pojo.Role;
import pojo.User;

/**
 *
 * @author ccsl-pc
 */
public class RegistrationPage extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationPage
     */
    RoleServices srvc = new RoleServices();
    UserDBServices dbsrvc = new UserDBServices();
        
    public RegistrationPage() {
        initComponents();        
        addTableNamesInComboBox((ArrayList<Role>) srvc.getRoles());
        showDataInTable((ArrayList<User>) dbsrvc.getUsers());       
    }
    
    private void showDataInTable( ArrayList<User> users){
        DefaultTableModel model = (DefaultTableModel) tbl_usersData.getModel();
        model.setRowCount(0);
        for (User user : users) {
            addToTable(user);
        }
    }
    public void addTableNamesInComboBox(ArrayList<Role> roles) {
        for (Role role : roles) {
            com_roleList.addItem(role.getRoleName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t_Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_pass1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        com_roleList = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        t_pass2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_mobile = new javax.swing.JTextField();
        btn_registerUser = new javax.swing.JButton();
        btn_editUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_usersData = new javax.swing.JTable();
        lbl_msgs = new javax.swing.JLabel();
        btn_dlt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Role");

        com_roleList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        com_roleList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Roles" }));
        com_roleList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                com_roleListItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Confirm Password");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Mobile");

        btn_registerUser.setText("Register");
        btn_registerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerUserActionPerformed(evt);
            }
        });

        btn_editUser.setText("Update");
        btn_editUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editUserActionPerformed(evt);
            }
        });

        tbl_usersData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Username", "Email", "Role", "Mobile"
            }
        ));
        tbl_usersData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_usersDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_usersData);

        btn_dlt.setText("Delete");
        btn_dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_dlt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_pass2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(t_Name)
                            .addComponent(t_username, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(t_email, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(com_roleList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_mobile, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(t_pass1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_registerUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_editUser))
                            .addComponent(lbl_msgs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(com_roleList, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_msgs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registerUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_dlt)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerUserActionPerformed
        // TODO add your handling code here:
        String name = t_Name.getText().trim();
        String userName = t_username.getText().trim();
        String email = t_email.getText().trim();
        String role_name = com_roleList.getSelectedItem().toString();
        String mobile = t_mobile.getText().trim();
        String pass1 = t_pass1.getText().trim();
        String pass2 = t_pass2.getText().trim();

        UserDBServices usrService = new UserDBServices();

        Role role = usrService.getRoleByRoleName(role_name);

        User user = new User(name, userName, email, role, mobile, pass1);
        addToTable(user);

        if (usrService.isEmailExists(email)) {
            lbl_msgs.setText("Email already exists!!");
        } else {
            int isSaved = usrService.saveUser(user);

            if (isSaved > 0) {
                t_Name.setText("");
                t_username.setText("");
                t_email.setText("");
                com_roleList.setSelectedItem("");
                t_mobile.setText("");
                t_pass1.setText("");
                t_pass2.setText("");
                lbl_msgs.setText("Data saved");
                
                clear();
            } else {
                lbl_msgs.setText("Failed to save!!");
            }
        }


    }//GEN-LAST:event_btn_registerUserActionPerformed

    static User user;

    private void btn_editUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editUserActionPerformed
        // TODO add your handling code here:
        String name = t_Name.getText().trim();
        String userName = t_username.getText().trim();
        String email = t_email.getText().trim();
        String role_name = com_roleList.getSelectedItem().toString();
        String mobile = t_mobile.getText().trim();
        String pass1 = t_pass1.getText().trim();
        String pass2 = t_pass2.getText().trim();


        Role role = dbsrvc.getRoleByRoleName(role_name);

        user.setName(name);
        user.setUserName(userName);
        user.setEmail(email);
        user.setRole(dbsrvc.getRoleByRoleName(role_name));
        user.setMobile(mobile);
        user.setPass(pass1);

        int isUpdated = dbsrvc.update(user);

        if (isUpdated > 0) {
            lbl_msgs.setText("Data saved");
            showDataInTable((ArrayList<User>) dbsrvc.getUsersByRole(role_name)); 
            clear();
        } else {
            lbl_msgs.setText("Failed to save!!");
        }


    }//GEN-LAST:event_btn_editUserActionPerformed

    private void tbl_usersDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usersDataMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_usersData.getModel();
        int selectedRow = tbl_usersData.getSelectedRow();

        t_Name.setText(model.getValueAt(selectedRow, 0).toString());
        t_username.setText(model.getValueAt(selectedRow, 1).toString());
        t_email.setText(model.getValueAt(selectedRow, 2).toString());
        com_roleList.setSelectedItem(model.getValueAt(selectedRow, 3).toString());
        t_mobile.setText(model.getValueAt(selectedRow, 4).toString());

        UserDBServices usrService = new UserDBServices();
        user = usrService.getUserByEmail(model.getValueAt(selectedRow, 2).toString().trim());
    }//GEN-LAST:event_tbl_usersDataMouseClicked

    private void btn_dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dltActionPerformed
        // TODO add your handling code here:
        UserDBServices usrService = new UserDBServices();
        usrService.delete(user.getId());
        showDataInTable((ArrayList<User>) dbsrvc.getUsersByRole(user.getRole().getRoleName())); 
    }//GEN-LAST:event_btn_dltActionPerformed

    private void com_roleListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_com_roleListItemStateChanged
        // TODO add your handling code here:
        String role_name = com_roleList.getSelectedItem().toString();
        
        if(role_name.equals("All Roles")){
            showDataInTable((ArrayList<User>) dbsrvc.getUsers());    
        }else{
            showDataInTable((ArrayList<User>) dbsrvc.getUsersByRole(role_name));
        }
        
       
    }//GEN-LAST:event_com_roleListItemStateChanged
    
    //Clear method
    public void clear(){
        t_Name.setText("");
        t_username.setText("");
        t_email.setText("");
        com_roleList.setSelectedItem("");
        t_mobile.setText("");
        t_pass1.setText("");
        t_pass2.setText("");
    }
    
    //Adding to table
    public void addToTable(User user) {
        DefaultTableModel model = (DefaultTableModel) tbl_usersData.getModel();

        Object[] obj = new Object[6];
        obj[0] = user.getName();
        obj[1] = user.getUserName();
        obj[2] = user.getEmail();
        obj[3] = user.getRole().getRoleName();
        obj[4] = user.getMobile();
        obj[5] = user.getPass();

        model.addRow(obj);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dlt;
    private javax.swing.JButton btn_editUser;
    private javax.swing.JButton btn_registerUser;
    private javax.swing.JComboBox<String> com_roleList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_msgs;
    private javax.swing.JTextField t_Name;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_mobile;
    private javax.swing.JTextField t_pass1;
    private javax.swing.JTextField t_pass2;
    private javax.swing.JTextField t_username;
    private javax.swing.JTable tbl_usersData;
    // End of variables declaration//GEN-END:variables
}
